export const BANNERS = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop",
        title: "50% İndirim",
        subtitle: "Bugüne özel tüm ürünlerde",
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1000&auto=format&fit=crop",
        title: "Yeni Gelenler",
        subtitle: "2026 Yaz Koleksiyonu",
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1000&auto=format&fit=crop",
        title: "Büyük İndirim",
        subtitle: "Ayakkabılarda %70'e varan indirim",
    },
];

export const formatDate = (dateString: string) => {
    const options: Intl.DateTimeFormatOptions = { year: "numeric", month: "short", day: "numeric" };
    return new Date(dateString).toLocaleDateString(undefined, options);
};

export const dummyProducts = [
    {
        ratings: {
            average: 4.7,
            count: 95,
        },
        _id: "698442cfda74ab16485b6060",
        name: "Yazlık Elbise",
        description: "Çiçek desenli, hafif ve ferah yazlık elbise.",
        price: 55,
        images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["XS", "S", "M", "L"],
        category: "Kadın",
        stock: 45,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683db0d7f779795ecfa9907",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Günlük kullanım için hafif ve rahat kesimli kot ceket.",
        price: 84,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 61,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 4.6,
            count: 50,
        },
        _id: "698442cfda74ab16485b6061",
        name: "Koşu Ayakkabısı",
        description: "Hız ve konfor için tasarlanmış hafif koşu ayakkabısı.",
        price: 79.99,
        comparePrice: 99.99,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
        category: "Ayakkabı",
        stock: 14,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 4.9,
            count: 200,
        },
        _id: "698442cfda74ab16485b605f",
        name: "Kot Ceket",
        description: "Her kombinle uyumlu klasik kot ceket. Dayanıklı ve şık.",
        price: 89.99,
        images: ["https://images.unsplash.com/photo-1559551409-dadc959f76b8?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["S", "M", "L", "XL"],
        category: "Erkek",
        stock: 20,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.824Z",
    },
    {
        ratings: {
            average: 4.5,
            count: 85,
        },
        _id: "698442cfda74ab16485b605e",
        name: "Günlük Kapüşonlu Sweatshirt",
        description: "Günlük kullanım için rahat kapüşonlu sweatshirt. Yumuşak pamuklu kumaş ve rahat kalıp.",
        price: 45,
        comparePrice: 60,
        images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 29,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.824Z",
    },
    {
        ratings: {
            average: 4.9,
            count: 30,
        },
        _id: "698442cfda74ab16485b6062",
        name: "Deri Çanta",
        description: "Geniş saklama alanına sahip premium deri çanta.",
        price: 129.99,
        images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1000&auto=format&fit=crop"],
        sizes: ["Tek Beden"],
        category: "Çanta",
        stock: 9,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-05T07:12:15.825Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d3d47f779795ecfa98a3",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaştan üretilmiş, rahat kesimli ve günlük kullanıma uygun tişört.",
        price: 80,
        images: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_1.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_2.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_3.png",
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2_4.png",
        ],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5417f779795ecfa98b3",
        name: "Erkek Dar Paça Klasik Pantolon",
        description: "Rahat kesimi ve şık görünümüyle günlük ve klasik kombinler için uygun pantolon.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img10.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8097f779795ecfa98d9",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Yumuşak kumaşıyla konfor sunan, günlük kullanıma uygun kadın bluz.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img5.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4937f779795ecfa98a9",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Günlük kullanım için rahat kesimli, pamuklu kadın bluz.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img29.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4d97f779795ecfa98ad",
        name: "Erkek Dar Paça Klasik Pantolon",
        description: "Şık duruşu ve rahat kesimiyle günlük kullanıma uygun pantolon.",
        price: 70,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img7.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da5f7f779795ecfa98f9",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Modern slim fit kesimli, günlük kullanıma uygun kot ceket.",
        price: 86,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img45.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683dac47f779795ecfa9901",
        name: "Çocuk Dar Kesim Pantolon",
        description: "Günlük kullanım için rahat ve dayanıklı çocuk pantolonu.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img49.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d71c7f779795ecfa98cd",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaştan üretilmiş, rahat kesimli çocuk tişörtü.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img23.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9847f779795ecfa98ef",
        name: "Erkek Slim Fit Kot Ceket",
        description: "ahat kullanım sunan, modern kesimli kot ceket.",
        price: 77,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img40.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9d07f779795ecfa98f3",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Günlük kullanım için rahat ve hafif çocuk tişörtü.",
        price: 25,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5217f779795ecfa98b1",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Yumuşak kumaşıyla konfor sunan, günlük kullanıma uygun kız çocuk bluzu.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6a57f779795ecfa98c7",
        name: "Kadın Kemerli Palazzo Pantolon",
        description: "Bel kemeri detayıyla şık, rahat kesimli palazzo pantolon.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img20.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9b27f779795ecfa98f1",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Rahat kesimiyle gün boyu konfor sağlayan pamuklu tişört.",
        price: 54,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img41.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7737f779795ecfa98d1",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Günlük kullanıma uygun, yumuşak kumaşlı kız çocuk bluzu.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img25.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6887f779795ecfa98c5",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Yumuşak ve hafif kumaşıyla günlük kullanıma uygun çocuk tişörtü.",
        price: 36,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img19.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d82b7f779795ecfa98db",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Rahat kesimli, günlük kullanıma uygun kız çocuk bluzu.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.829Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5647f779795ecfa98b5",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaşıyla günlük kullanıma uygun rahat tişört.",
        price: 46,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img11.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d89d7f779795ecfa98e1",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Yumuşak kumaşı ve rahat kalıbıyla günlük kullanıma uygun bluz.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da147f779795ecfa98f7",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Günlük kullanım için rahat kesimli, fermuarlı kadın ceket.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img44.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d91f7f779795ecfa98eb",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaştan üretilmiş, günlük kullanıma uygun tişört.",
        price: 48,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 95,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683db0d7f779795ecfa9907",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Hafif ve rahat yapısıyla günlük kullanıma uygun slim fit kot ceket.",
        price: 84,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 61,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d42b7f779795ecfa98a5",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Günlük kullanım için rahat kesimli kız çocuk bluzu.",
        price: 50,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6dc7f779795ecfa98cb",
        name: "Kadın Kemerli Palazzo Pantolon",
        description: "Rahat kesimli ve şık duruşlu palazzo pantolon.",
        price: 67,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img22.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5987f779795ecfa98b9",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Günlük kullanım için rahat kalıplı, pamuklu kadın bluz.",
        price: 45,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6057f779795ecfa98bf",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Yumuşak kumaşıyla günlük kullanıma uygun kız çocuk bluzu.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img16.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8467f779795ecfa98dd",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Rahat kesimli, günlük kullanıma uygun pamuklu tişört.",
        price: 34,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img31.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d90a7f779795ecfa98e9",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Konforlu kumaşıyla günlük kullanıma uygun kadın bluz.",
        price: 42,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d9fa7f779795ecfa98f5",
        name: "Çocuk Dar Kesim Pantolon",
        description: "Rahat kullanım sunan, günlük kullanıma uygun çocuk pantolonu.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img43.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683daa27f779795ecfa98ff",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Modern kesimli, günlük kullanıma uygun slim fit kot ceket.",
        price: 80,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img48.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8b37f779795ecfa98e3",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Rahat kalıplı, günlük kullanıma uygun pamuklu kadın bluz.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img34.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6547f779795ecfa98c3",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Rahat kesimli, günlük kullanıma uygun pamuklu çocuk tişörtü.",
        price: 28,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4f47f779795ecfa98af",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaşıyla günlük kullanıma uygun tişört.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d57d7f779795ecfa98b7",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Rahat kesimli, günlük kullanıma uygun pamuklu tişört.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img12.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6387f779795ecfa98c1",
        name: "Erkek Dar Paça Klasik Pantolon",
        description: "Rahat kesimli, günlük ve klasik kombinler için uygun pantolon.",
        price: 63,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img17.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d6c47f779795ecfa98c9",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Rahat kesimli ve günlük kullanıma uygun fermuarlı kadın ceket.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img21.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da717f779795ecfa98fb",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Modern kesimiyle günlük kullanıma uygun slim fit kot ceket.",
        price: 72,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7b57f779795ecfa98d5",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Günlük kullanıma uygun, rahat kesimli kız çocuk bluzu.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d3947f779795ecfa98a1",
        name: "Kadın Bisiklet Yaka Pamuklu Bluz",
        description: "Günlük kullanım için rahat kesimli pamuklu kadın bluz.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img1.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4587f779795ecfa98a7",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Rahat kalıplı, günlük kullanıma uygun pamuklu tişört.",
        price: 26,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img4.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7567f779795ecfa98cf",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Günlük kullanım için rahat kesimli pamuklu çocuk tişörtü.",
        price: 30,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img24.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d79e7f779795ecfa98d3",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Günlük kullanım için rahat kesimli fermuarlı kadın ceket.",
        price: 82,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img26.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d7d57f779795ecfa98d7",
        name: "Erkek Slim Fit Kot Ceket",
        description: "Rahat kesimli, günlük kullanıma uygun slim fit kot ceket.",
        price: 79,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img28.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8f27f779795ecfa98e7",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Rahat kesimli, günlük kullanıma uygun fermuarlı kadın ceket.",
        price: 78,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img36.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d94e7f779795ecfa98ed",
        name: "Erkek Baskılı Pamuklu Gömlek",
        description: "Günlük kullanım için rahat kesimli, pamuklu erkek gömlek.",
        price: 52,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img39.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683dadf7f779795ecfa9903",
        name: "Çocuk Dar Kesim Pantolon",
        description: "Hafif ve rahat yapısıyla günlük kullanıma uygun çocuk pantolonu.",
        price: 40,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683daf67f779795ecfa9905",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Rahat kesimiyle konfor sunan, fermuarlı kadın ceket.",
        price: 68,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img51.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: true,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d4b27f779795ecfa98ab",
        name: "Kız Çocuk Pamuklu Bluz",
        description: "Rahat kesimli, günlük kullanıma uygun kız çocuk bluzu.",
        price: 56,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5e07f779795ecfa98bd",
        name: "Erkek Dar Paça Klasik Pantolon",
        description: "Şık görünümüyle günlük ve klasik kombinlere uygun pantolon.",
        price: 58,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img15.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8d17f779795ecfa98e5",
        name: "Kadın Fermuarlı Rahat Kesim Ceket",
        description: "Günlük kullanım için rahat kesimli fermuarlı kadın ceket.",
        price: 74,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Kadın",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d5b67f779795ecfa98bb",
        name: "Erkek Çocuk Pamuklu Tişört",
        description: "Yumuşak pamuklu kumaştan üretilmiş, günlük kullanıma uygun çocuk tişörtü.",
        price: 60,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683d8897f779795ecfa98df",
        name: "Erkek Bisiklet Yaka Pamuklu Tişört",
        description: "Rahat kesimli, günlük kullanıma uygun pamuklu tişört.",
        price: 64,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Erkek",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
    {
        ratings: {
            average: 0,
            count: 0,
        },
        _id: "6683da887f779795ecfa98fd",
        name: "Çocuk Dar Kesim Pantolon",
        description: "Rahat kesimi ve dayanıklı yapısıyla günlük kullanıma uygun çocuk pantolonu.",
        price: 38,
        images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        category: "Çocuk",
        stock: 100,
        isFeatured: false,
        isActive: true,
        createdAt: "2026-02-08T04:21:50.830Z",
    },
];

export const dummyWishlist = [dummyProducts[3], dummyProducts[10], dummyProducts[6]];

export const dummyCart = {
    _id: "6984434e30be1ba0cf5d0fd4",
    user: "69819801a872c913f84d13f4",
    items: [
        {
            product: {
                _id: "6683d91f7f779795ecfa98eb",
                name: "Erkek Bisiklet Yaka Pamuklu Tişört",
                price: 48,
                images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png"],
                stock: 95,
            },
            quantity: 1,
            price: 48,
            size: "M",
            _id: "698952e1ef9d0c746ef827b9",
        },
        {
            product: {
                _id: "6683d4f47f779795ecfa98af",
                name: "Erkek Bisiklet Yaka Pamuklu Tişört",
                price: 68,
                images: ["https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png"],
                stock: 100,
            },
            quantity: 1,
            price: 68,
            size: "L",
            _id: "698952f5ef9d0c746ef827c6",
        },
    ],
    totalAmount: 116,
    createdAt: "2026-02-05T07:14:22.429Z",
};

export const dummyUser = {
    _id: "69819801a872c913f84d13f4",
    name: "Programmer Yavuz",
    email: "programmeryavuz@example.com",
    firstName: "Programmer",
    lastName: "Yavuz",
    imageUrl: "https://avatars.githubusercontent.com/u/109480983",
    emailAddresses: [
        {
            emailAddress: "programmeryavuz@example.com",
        },
    ],
    clerkId: "user_396E235",
    role: "admin",
    publicMetadata: {
        role: "admin",
    },
};